### PR TITLE
changed error messages

### PR DESCRIPTION
**Pull request by braydenc303**

### CODE REVIEW

**Comment by haxwell** [comment]
I updated issue #1 with a bit more detail about the steps to reproduce, and the expected vs actual behavior.

**Comment by braydenc303** [comment]
Also updated the placeholder and messages for the phone field.

**Comment by haxwell** [comment]
SO close!

Thanks for changing the placeholder text in the phone number field, too.

The problem I am seeing is that it is validating the text, in both the email and phone fields, before the user exits the field. 

To reproduce,

1. Click I Am New Here.
2. Enter valid name
3. Enter a single character in the email OR phone field.

Actual: We see the error message, telling us the value of the field is not valid.
Expected: As the user is typing in the field, there should be no error message. That should only appear once the user has left the field.

- Validation on a field, error messages etc, should not happen until you exit the field. 
- If you begin typing in the field, it should clear the error message. 
- If there is nothing in the field, there should be no error message.

**Comment by braydenc303** [comment]
I have validation happening on blur now. I do not know how to accomplish the second bullet point:

- If you begin typing in the field, it should clear the error message.

either onBlur or onChange. The error message that is present upon the previous onBlur stays in place until the next onBlur where it is either valid, or has the same, or a different error message.

**Comment by haxwell** [comment]
I am smiling ear to ear!

That's awesome, yes, I went through all the cases I could think of and there it is.. The code handles all of them. Nice.

I will merge this to the main Dev branch.

There are a few more polishes I can think of, and then we can merge it into Master.

**Comment by haxwell** [comment]
Actually, now that I'm looking at it, only one polish: Remove the comments at the end of the file.

**Comment by haxwell** [comment]
And the Cypress tests.

**Pull request merged**
